/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhitepaperRouteImport } from './routes/whitepaper'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const WhitepaperRoute = WhitepaperRouteImport.update({
  id: '/whitepaper',
  path: '/whitepaper',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/whitepaper': typeof WhitepaperRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/whitepaper': typeof WhitepaperRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/whitepaper': typeof WhitepaperRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/whitepaper' | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/whitepaper' | '/lovable/email/transactional/preview'
  id: '__root__' | '/' | '/whitepaper' | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WhitepaperRoute: typeof WhitepaperRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whitepaper': {
      id: '/whitepaper'
      path: '/whitepaper'
      fullPath: '/whitepaper'
      preLoaderRoute: typeof WhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WhitepaperRoute: WhitepaperRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
